recipient_name: "Whom it may concern"
role_title: "Fullstack Software Engineer"
company_name: "Envoy"
job_board: "LinkedIn"
company_specific_mention: "commitment to fostering a positive workplace environment through well-designed user experiences"
your_name: "John Marren"

